# Generated by Django 4.0.5 on 2022-07-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_autor_options_livros_editora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='livros',
            name='ISBN',
            field=models.CharField(max_length=13),
        ),
    ]
